app/meeting/__init__.py
from flask import Blueprint

bp_meeting = Blueprint("meeting", __name__, static_folder = "static", template_folder ="templates")

from app.meeting import routes

app/meeting/routes.py
from flask import render_template, redirect, url_for, flash, request
from werkzeug.urls import url_parse
from flask_login import login_user, logout_user, current_user
from app import db
from app.meeting import bp_meeting
# from app.auth.forms import LoginForm, RegistrationForm, \
#     ResetPasswordRequestForm, ResetPasswordForm
from app.models import *
from app.meeting.form import *
from app.meeting.email import *
from sqlalchemy import and_

#--------------------------------------------------------
@bp_meeting.route("/create_meeting", methods=["GET", "POST"])
def create_meeting():
    form = createMeetingForm()
    if form.validate_on_submit():
        # add data to meeting table
        meetingName = form.meetingName.data
        meetingDescription = form.meetingDescription.data
        meetingDate = form.meetingDate.data
        meetingStart =  form.meetingStart.data
        meetingEnd = form.meetingEnd.data
        NewMetting= Meeting(meeting_name = meetingName, meeting_description=meetingDescription, meeting_date=meetingDate, meeting_start=meetingStart, meeting_end=meetingEnd)
        db.session.add(NewMetting)

        #add data to meeting_user table and send email
        users = User.query.all()
        for user in users:
            send_meeting_email(user, NewMetting)
            newMeetingUser = Meeting_user(user_id=user.id, meeting_id = NewMetting.id)
            db.session.add(newMeetingUser)
        db.session.commit()

        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main.index'))
    return render_template("create_meeting.html", form=form)

#--------Meeting confirmation------------------------------------------------
@bp_meeting.route('/meeting_confirmation/<meetingId>/<token>', methods=['GET', 'POST'])
def meeting_confirmation(token, meetingId):
    user = User.verify_meeting_confirmation_token(token)

    if not user:
        return redirect(url_for('main.index'))
    form = meetingConfirmationForm()
    meetingUser = Meeting_user.query.filter(and_(Meeting_user.user_id == user.id, Meeting_user.meeting_id == meetingId)).first()
    meeting = Meeting.query.get(meetingId)

    if form.validate_on_submit():
        meetingUser.is_responded = True
        meetingUser.is_attended = bool(form.isAttended.data)
        meetingUser.response_date = datetime.now()
        numberOfResponses = Meeting_user.query.filter(and_(Meeting_user.is_responded == True, Meeting_user.meeting_id == meetingId)).count()
        meeting.number_of_responses = numberOfResponses
        db.session.commit()
        return redirect(url_for('main.index'))

    return render_template('meeting_confirmation.html', form=form, meetingUser=meetingUser, meeting=meeting)

#--------View all meetings------------------------------------------------
@bp_meeting.route('/view_all_meetings', methods=['GET', 'POST'])
def view_all_meetings():
    meetings = Meeting.query.order_by(Meeting.meeting_date.desc()).all()
    return render_template('view_all_meetings.html', meetings=meetings)

#--------View all meetings------------------------------------------------
@bp_meeting.route('/edit_meeting_details/<meetingId>', methods=['GET', 'POST'])
def edit_meeting_details(meetingId):
    meeting = Meeting.query.get(meetingId)
    form = editMeetingForm(meetingDescription = meeting.meeting_description, meetingNote = meeting.meeting_note)
    return render_template('edit_meeting_details.html', meeting=meeting, form = form)

app/meeting/templates/create_meeting.html
{% extends "layout.html" %}

{% block title %}
    Create new meeting
{% endblock %}

{% block body %}
    <h1>Create new meeting</h1>

    <form action="" method="post">
      {{ form.hidden_tag() }}
      <p>
          {{ form.meetingName.label }}<br>
          {{ form.meetingName }}<br>
          {% for error in form.meetingName.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingDescription.label }}<br>
          {{ form.meetingDescription }}<br>
          {% for error in form.meetingDescription.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingDate.label }}<br>
          {{ form.meetingDate }}<br>
          {% for error in form.meetingDate.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingStart.label }}<br>
          {{ form.meetingStart }}<br>
          {% for error in form.meetingStart.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingEnd.label }}<br>
          {{ form.meetingEnd }}<br>
          {% for error in form.meetingEnd.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>{{ form.submit() }}</p>

    </form>
{% endblock %}

app/meeting/templates/edit_meeting_details.html
{% extends "layout.html" %}

{% block title %}
    Update meeting information
{% endblock %}

{% block body %}
    <h1>Update meeting information</h1>

    <form action="" method="post">
      {{ form.hidden_tag() }}
      <p>
          {{ form.meetingName.label }}<br>
          {{ form.meetingName(value=meeting.meeting_name) }}<br>
          {% for error in form.meetingName.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingDescription.label }}<br>
          {{ form.meetingDescription(value=meeting.meeting_description)  }}<br>
          {% for error in form.meetingDescription.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingNote.label }}<br>
          {{ form.meetingNote(value=meeting.meeting_note) }}<br>
          {% for error in form.meetingNote.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingDate.label }}<br>
          {{ form.meetingDate(value=meeting.meeting_date) }}<br>
          {% for error in form.meetingDate.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingStart.label }}<br>
          {{ form.meetingStart(value=meeting.meeting_start) }}<br>
          {% for error in form.meetingStart.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>
          {{ form.meetingEnd.label }}<br>
          {{ form.meetingEnd(value=meeting.meeting_end) }}<br>
          {% for error in form.meetingEnd.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>{{ form.submit() }}</p>

    </form>
{% endblock %}

app/meeting/templates/meeting_confirmation.html
{% extends "layout.html" %}

{% block title %}
    Create new meeting
{% endblock %}

{% block body %}
    <h1>Confirm attend or not from meeting {{ meeting.meeting_name }}</h1>

    <form action="" method="post">
      {{ form.hidden_tag() }}
      <p>
          {{ form.isAttended.label }}<br>
          {{ form.isAttended }}<br>
          {% for error in form.isAttended.errors %}
          <span style="color: red;">[{{ error }}]</span>
          {% endfor %}
      </p>
      <p>{{ form.submit() }}</p>

    </form>
{% endblock %}

app/meeting/templates/meeting_invatation.html
<h1>Kính gửi thầy/cô {{ user.username }},</h1>
<p>
    Kính mời thầy/cô tới dự cuộc họp {{ meeting.meetingName}} vào lúc {{ meeting.meeting_start}} ngày {{ meeting.meeting_date}}
    De vao xem thong tin va tra loi cuoc hop, thay/co bam vao link sau {{ meetingId }} 1234
    <a href="{{ url_for('meeting.meeting_confirmation', meetingId = meetingId, token=token, _external=True) }}">
       click here
     </a>.
</p>

app/meeting/templates/view_all_meetings.html
{% extends "layout.html" %}

{% block title %}
    staffs
{% endblock %}

{% block body %}
    <h1>All Meeting</h1>
      <form action="" method="post">
      <table class="table" border=2px>
        <thead>
          <tr>
            <th>Select</th>
            <th>Meeting Name</th>
            <th>Meeting Descriptions</th>
            <th>Meeting Date</th>
            <th>Number of Responses</th>
          </tr>
        </thead>
        <tbody>
          {% for meeting in meetings %}
            {% if ((meeting.id % 2)==1) %}
              <tr class="success">
                <td> <input type=checkbox name="checkbox" value="{{meeting.id}}"></td>
                <td><a href="{{ url_for('meeting.edit_meeting_details', meetingId = meeting.id) }}">{{meeting.meeting_name}}</a></td>
                <td>{{meeting.meeting_description}}</td>
                <td>{{meeting.meeting_date}}</td>
                <td>{{meeting.number_of_responses}}</td>
              </tr>
            {% else %}
              <tr class="Warning">
                <td> <input type=checkbox name='checkbox' value="{{meeting.id}}"></td>
                <td><a href="{{ url_for('meeting.edit_meeting_details', meetingId = meeting.id) }}">{{meeting.meeting_name}}</a></td>
                <td>{{meeting.meeting_description}}</td>
                <td>{{meeting.meeting_date}}</td>
                <td>{{meeting.number_of_responses}}</td>
              </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>

      <div class="form-group">
          <button class="btn btn-danger">Delete selected meeting</button>
      </div>
      </form>
{% endblock %}